version: '3.8'

services:
  backend:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: chat-backend
    ports:
      - "4400:4400"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - chat-network

  mongodb:
    image: mongo:latest
    container_name: chat-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=chatapp
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  mongodb-data: